services:
  db: 
    image: postgres:16
    container_name: outfitDB
    environment:
      POSTGRES_DB: outfit
      POSTGRES_PASSWORD: outfit
      POSTGRES_USER: outfit
    ports:
      - "5432:5432"
    volumes:
      - outfitDBdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U outfit -d outfit"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  outfitDBdata:
